version: '3.9'
services:

  client:
    container_name: 'iota_client'
    image: node
    depends_on:
      - server
    volumes:
      - ./client:/client
    working_dir: "/client"
    env_file:
      - ./client/.env
    environment:
        PORT: 3000
        API_URL: http://host.docker.internal:4000 ## There's a bug in node fetch that can't resolve localhost so using docker hostname instead
        DASHBOARD_URL: http://localhost:5000
    entrypoint: "/bin/bash -c"
    command:
      - "npm run dev"
    ports:
      - 3000:3000
      
  client2:
    container_name: 'iota_client2'
    image: node
    depends_on:
      - server
    volumes:
      - ./client2:/client2
    working_dir: "/client2"
    env_file:
      - ./client2/.env
    environment:
        PORT: 3001
        API_URL: http://host.docker.internal:4000 ## There's a bug in node fetch that can't resolve localhost so using docker hostname instead
        DASHBOARD_URL: http://localhost:5000
    entrypoint: "/bin/bash -c"
    command:
      - "npm run dev"
    ports:
      - 3001:3001
      
  db:
    container_name: 'iota_db'
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/data/postgres
    environment:
      POSTGRES_USER: iota
      POSTGRES_PASSWORD: RandomPassword
      PGDATA: /data/postgres

  server:
    container_name: 'iota_server'
    image: node
    depends_on:
      - db
    volumes:
      - ./server:/server
    working_dir: "/server"
    env_file:
      - ./server/.env
    environment:
        PORT: 4000
        CLIENT_URL: http://localhost:3000
        DASHBOARD_URL: http://localhost:5000
    entrypoint: "/bin/bash -c"
    command:
      - "npm run dev"
    ports:
      - 4000:4000
      - 5555:5555
  
  dashboard:
    container_name: 'iota_dashboard'
    image: node
    depends_on:
      - db
    volumes:
      - ./dashboard:/dashboard
    working_dir: "/dashboard"
    environment:
        PORT: 5000
    entrypoint: "/bin/bash -c"
    command:
      - "npm run dev"
    ports:
      - 5000:5000

volumes:
  db-data:
    name: iota-data

