import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { Button } from "../components/Form";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Iota Admin Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center h-screen">
        <h1 className="text-5xl text-indigo-800 m-6">Admin login</h1>
        <AdminAuth />
      </div>
    </>
  );
};

export default Home;

const AdminAuth = () => {
  const { data: sessionData } = useSession();

  return (
    <Button classNames="m-6 p-3" onClick={sessionData ? () => void signOut() : () => void signIn("github", {
      callbackUrl: `${window.location.origin}/dashboard`,
    })}>{sessionData ? "Sign out" : "Sign in"}</Button>
  );
};
